### ISSUE TITLE
Pull na Branch

### ISSUE THREAD

**Issue by Lidianeangelo** [reprograma/on6-xp-s2-logica-js#14]
Isa, tudo bem?

Dúvida minha e de algumas meninas: Precisa subir a pastinha do readline-sync na nossa branch ou somente o arquivo da calculadora?
Brigada!

**Comment by isabellegalvao** [comment]
Não precisa subir a pasta do readline-sync nem a node-modules, pode subir apenas o arquivo da calculadora e o arquivo package.json
