### ISSUE TITLE
Case-sensitive

### ISSUE THREAD

**Issue by TainaraMoreno** [reprograma/on6-xp-s2-logica-js#17]
Uma duvida, o JS é case-sensitive. Tem alguma forma de tratar isso para a resposta do usuário? 
Ex.: 
if(tempo === "**S**ol"){

    console.log("Vai a praia!!")

Porem o usuário responde:  **s**ol (com o s minusculo), mas no código o está com S Maiúsculo. 
Sendo assim programa retorna:  Atividade NÃO encontrada. 

Então teria alguma forma do programa entender a resposta mesmo sendo maiúsculo ou minúsculo?

**Comment by isabellegalvao** [comment]
Nesse momento inicial que a gente está uma solução simples seria perguntar duas vezes, com maiúscula e com minúscula, pode usar por exemplo || ou lógico ou fazer um segundo if.

Se você quiser se aprofundar da pra usar um conceito chamado Regex ou Expressão Regular que pode endereçar essa questão de um jeito mais simples, mas é um conteúdo mais chatinho de entender.

Mas pra esse momento eu não vou me preocupar se no seu código tiver só o minúsculo por exemplo
