### ISSUE TITLE
Problema com os caracteres no terminal

### ISSUE THREAD

**Issue by monalizavitor** [reprograma/on6-xp-s2-logica-js#20]
O terminal não está reconhecendo as letras como caracteres comuns. O que será que ta acontecendo? 

![erro](https://user-images.githubusercontent.com/65304621/90702774-838dc480-e262-11ea-9af7-994e468400a6.jpeg)

**Comment by isabellegalvao** [comment]
Tenta isso:

`const nota = readline.question('Qual foi a sua nota? ', {
  encoding: 'utf8'
});`

**Comment by monalizavitor** [comment]
Deu certo só na primeira linha 
![image](https://user-images.githubusercontent.com/65304621/90812514-9a80f500-e2fc-11ea-95a3-655d7059d394.png)

**Comment by isabellegalvao** [comment]
Parece um problema do interpretador de linha de comando no Windows 10, [aqui](https://github.com/anseki/readline-sync/issues/86) tem uma issue do readline-sync que aborda isso. 

Não existe solução de fazer funcionar com o `readline-sync` o jeito foi trocar de biblioteca.

1. Desinstalar o readline-sync
`npm uninstall readline-sync` 

2. Instalar outra biblioteca de input de usuário, sugestão [synchronous-user-input](https://www.npmjs.com/package/synchronous-user-input)
`npm i synchronous-user-input` 

3. Testar
```js
var pergunta = require('synchronous-user-input');
 
var nome = pergunta('Digite seu nome: ');
console.log("Olá, " + name + "!");
```
