### ISSUE TITLE
Exercícios 

### ISSUE THREAD

**Issue by SimoniAccioly** [reprograma/on6-xp-s2-logica-js#22]
Olá Isabelle, boa noite!

Se puder, por favor nos envie mais exercícios... E se tiver alguma indicação de site onde tenham atividades por favor nos indique. 😊
Obrigada.

**Comment by isabellegalvao** [comment]
- Faça um programa que peça dois números inteiros e imprima a soma desses dois números

- Escreva um programa que leia um valor em metros e o exiba convertido em milímetros

- Escreva um programa que leia a quantidade de dias, horas, minutos e segundos do usuário. Calcule o total em segundos.

- Faça um programa que calcule o aumento de um salário. Ele deve solicitar o valor do salário e a porcentagem do aumento. Exiba o valor do aumento e do novo salário.

- Solicite o preço de uma mercadoria e o percentual de desconto. Exiba o valor do desconto e o preço a pagar.

- Converta uma temperatura digitada em Celsius para Fahrenheit. F = 9*C/5 + 32

- Faça agora o contrário, de Fahrenheit para Celsius.

- Sabendo que str() converte valores numéricos para string, calcule quantos dígitos há em 2 elevado a um milhão.

- Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário informe um valor válido.

- Faça um programa que leia um nome de usuário e a sua senha e não aceite a senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a pedir as informações.

- Faça um Programa que leia três números e mostre o maior deles.

- Faça um Programa que leia três números e mostre o maior e o menor deles.

**Comment by isabellegalvao** [comment]
Calcule o tempo de uma viagem de carro. Pergunte a distância a percorrer e a velocidade média esperada para a viagem.

**Comment by SimoniAccioly** [comment]
Obrigada 😊❤️
